### ISSUE TITLE
ERROR ON DEPLOY VERCEL

### ISSUE THREAD

**Issue by PHANTOMGOD2OP** [AntonioErdeljac/next13-airbnb-clone#21]
`

PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
--
11:12:58.640 |  
11:12:58.640 | Learn how: https://pris.ly/d/vercel-build
11:12:58.640 | at qa (/vercel/path0/node_modules/@prisma/client/runtime/library.js:161:69)
11:12:58.640 | at new t (/vercel/path0/node_modules/@prisma/client/runtime/library.js:174:3203)
11:12:58.640 | at 61306 (/vercel/path0/.next/server/chunks/627.js:141:37)
11:12:58.641 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
11:12:58.641 | at 18627 (/vercel/path0/.next/server/chunks/627.js:34:16)
11:12:58.641 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
11:12:58.641 | at 71673 (/vercel/path0/.next/server/app/api/favorites/[listingId]/route.js:153:22)
11:12:58.642 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
11:12:58.642 | at __webpack_exec__ (/vercel/path0/.next/server/app/api/favorites/[listingId]/route.js:265:39)
11:12:58.653 | at /vercel/path0/.next/server/app/api/favorites/[listingId]/route.js:266:78 {
11:12:58.653 | clientVersion: '4.14.1',
11:12:58.656 | errorCode: undefined
11:12:58.656 | }
11:12:58.657 |  
11:12:58.657 | > Build error occurred
11:12:58.658 | Error: Failed to collect page data for /api/favorites/[listingId]
11:12:58.658 | at /vercel/path0/node_modules/next/dist/build/utils.js:1152:15
11:12:58.658 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
11:12:58.659 | type: 'Error'
11:12:58.659 | }
11:12:58.759 | Error: Command "npm run build" exited with 1
11:12:59.075 | Deployment completed
11:12:59.025 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

'

**Comment by adham618** [comment]
add this to package.json     "postinstall": "prisma generate"
in scripts

**Comment by navi-05** [comment]
You can override the build command during Vercel deploy from 'next build' -> 'npx prisma generate && next build'

**Comment by sarthak-tirpude** [comment]
> 

This did not work

**Comment by abhising007** [comment]
Overriding next build with 'npx prisma generate && next build' worked for me.

**Comment by deribewsoftware** [comment]
"postinstall": "prisma generate",
    "build": "prisma generate && next build", on to package.json file and after that edit to on vercel deploy to Build run prisma generate && next build"
