### ISSUE TITLE
Cannot read properties of undefined (reading 'findUnique')

### ISSUE THREAD

**Issue by saeid4x** [AntonioErdeljac/next13-airbnb-clone#42]
when sign up by Github, i get below errors. how to fix this error??

`
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error Cannot read properties of undefined (reading 'findUnique') TypeError: Cannot read properties of undefined (reading 'findUnique')
    at getUserByEmail (J:\My-Projects\Next\airbnb-clone\node_modules\@next-auth\prisma-adapter\dist\index.js:208:43)
    at _callee2$ (J:\My-Projects\Next\airbnb-clone\node_modules\next-auth\core\errors.js:365:29)
    at tryCatch (J:\My-Projects\Next\airbnb-clone\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (J:\My-Projects\Next\airbnb-clone\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (J:\My-Projects\Next\airbnb-clone\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (J:\My-Projects\Next\airbnb-clone\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (J:\My-Projects\Next\airbnb-clone\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at J:\My-Projects\Next\airbnb-clone\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at J:\My-Projects\Next\airbnb-clone\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at callbackHandler (J:\My-Projects\Next\airbnb-clone\node_modules\next-auth\core\lib\callback-handler.js:169:49)
    at async Object.callback (J:\My-Projects\Next\airbnb-clone\node_modules\next-auth\core\routes\callback.js:119:13)
    at async AuthHandler (J:\My-Projects\Next\airbnb-clone\node_modules\next-auth\core\index.js:208:28)
    at async NextAuthApiHandler (J:\My-Projects\Next\airbnb-clone\node_modules\next-auth\next\index.js:22:19)
    at async NextAuth._args$ (J:\My-Projects\Next\airbnb-clone\node_modules\next-auth\next\index.js:106:14) {
  name: 'GetUserByEmailError',
  code: undefined
}
API handler should not return a value, received object.
API handler should not return a value, received object.
API handler should not return a value, received object.
[next-auth][warn][EXPERIMENTAL_API]
`getServerSession` is used in a React Server Component.
https://next-auth.js.org/configuration/nextjs#getServerSession}
https://next-auth.js.org/warnings#EXPERIMENTAL_API
[next-auth][warn][NEXTAUTH_URL]
https://next-auth.js.org/warnings#nextauth_url
[next-auth][warn][DEBUG_ENABLED]
https://next-auth.js.org/warnings#debug_enabled`

**Comment by RTE1818** [comment]
@AntonioErdeljac I commented on the YT video, I am also receiving this issue for both Github and Google OAuth. Any help is appreciated!

**Comment by fransachmadhw** [comment]
Recently I found the solution. Inside your [...nextauth].ts, change this
Before = import NextAuth, { AuthOptions } from 'next-auth'; 
After = import NextAuth, { NextAuthOptions } from 'next-auth';

Also
Before = export const authOptions: AuthOptions = {
After = export const authOptions: NextAuthOptions = {

Its referred to official nextauth demo
