### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by philip06lee** [AntonioErdeljac/next13-airbnb-clone#8]
Got this error below when deploying to Vercel. Anyone can help? Many thanks  :
Error: Invalid `prisma.listing.findMany()` invocation,
at getListings (/vercel/path0/.next/server/chunks/983.js:80:15)
at async Home (/vercel/path0/.next/server/app/page.js:480:22)

**Comment by Saif045** [comment]
you need to Allow Access from Anywhere from MongoDB Atlas in the ip whitelist https://medium.com/@tyler_48883/mongodb-atlas-connect-an-ip-make-it-public-delete-access-4-of-x-d18775ebf01f
